# modules/admission/repository.py

from __future__ import annotations
from typing import Any

from core.database.repository import BaseRepository

__all__ = ["AdmissionRepository"]


class AdmissionRepository(BaseRepository):
    """
    Handles all database interactions for the Admission entity.
    STRICT RULE: No business logic, validation, or default statuses allowed here.
    """

    def has_admission_in_state(self, student_id: int, status: str) -> bool:
        """
        Checks if the student already has an admission record in the specified status.
        Used to enforce the 'State-Restricted Multiple Admissions' policy.
        """
        query = "SELECT 1 FROM admissions WHERE student_id = ? AND status = ? LIMIT 1;"
        return self.exists(query, (student_id, status))

    def insert(self, admission_data: dict[str, Any]) -> int:
        """
        Inserts a new admission record.
        Returns the new Admission ID (Primary Key) generated by the database.
        """
        query = """
            INSERT INTO admissions (student_id, status)
            VALUES (?, ?);
        """
        params = (
            admission_data["student_id"],
            admission_data["status"]
        )
        
        return self.execute_insert(query, params)
